# Generated by Django 3.2.12 on 2022-05-20 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('genres', models.CharField(max_length=50)),
                ('descpription', models.TextField()),
                ('poster_path', models.CharField(max_length=300)),
                ('bookmark', models.ManyToManyField(blank=True, related_name='saved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
