# Generated by Django 3.2.12 on 2022-05-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220521_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mood',
            field=models.ManyToManyField(blank=True, to='movies.Mood'),
        ),
    ]
